In [4]:
a = rand(4,4)

4×4 Array{Float64,2}:
 0.0509664  0.460211  0.783801   0.10411  
 0.316647   0.756405  0.480274   0.183823 
 0.256588   0.17033   0.0322114  0.0699982
 0.467098   0.44969   0.685463   0.592504 

In [5]:
reshape(a,16,1)

16×1 Array{Float64,2}:
 0.0509664
 0.316647 
 0.256588 
 0.467098 
 0.460211 
 0.756405 
 0.17033  
 0.44969  
 0.783801 
 0.480274 
 0.0322114
 0.685463 
 0.10411  
 0.183823 
 0.0699982
 0.592504 

In [6]:
b = [true false false false; false true false false; false false true false; false false false true]

4×4 Array{Bool,2}:
  true  false  false  false
 false   true  false  false
 false  false   true  false
 false  false  false   true

In [7]:
a*b

4×4 Array{Float64,2}:
 0.0509664  0.460211  0.783801   0.10411  
 0.316647   0.756405  0.480274   0.183823 
 0.256588   0.17033   0.0322114  0.0699982
 0.467098   0.44969   0.685463   0.592504 

In [8]:
a[b]

4-element Array{Float64,1}:
 0.0509664
 0.756405 
 0.0322114
 0.592504 

In [9]:
a.*b

4×4 Array{Float64,2}:
 0.0509664  0.0       0.0        0.0     
 0.0        0.756405  0.0        0.0     
 0.0        0.0       0.0322114  0.0     
 0.0        0.0       0.0        0.592504

In [10]:
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [11]:
a*eye(4)

4×4 Array{Float64,2}:
 0.0509664  0.0       0.0        0.0     
 0.0        0.756405  0.0        0.0     
 0.0        0.0       0.0322114  0.0     
 0.0        0.0       0.0        0.592504

In [12]:
a.*eye(4)

4×4 Array{Float64,2}:
 0.0509664  0.0       0.0        0.0     
 0.0        0.756405  0.0        0.0     
 0.0        0.0       0.0322114  0.0     
 0.0        0.0       0.0        0.592504

In [20]:
c=rand(8)

8-element Array{Float64,1}:
 0.363457
 0.454172
 0.050764
 0.815543
 0.5211  
 0.945757
 0.3057  
 0.5095  

In [14]:
length(c)

8

In [15]:
size(c)

(8,)

In [16]:
size(a)

(4, 4)

In [17]:
length(a)

16

In [21]:
i=1;
while i<=length(c)
    println(c[i])
    if c[i] > 0.8
        break
    end
    i=i+1
end

0.3634568363446602
0.4541717174508966
0.05076399631653117
0.8155429667286538
